name: Deploy with changes

on:
  push:
    branches: [ "master" ]

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
  build_and_push:
    needs: lint
    uses: ./.github/workflows/build_push_docker_image.yaml
    secrets: 
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker pull ailurus1/text2image-bot:latest
          docker run --env TG_TOKEN=${{ secrets.TG_TOKEN }} --env HF_TOKEN=${{ secrets.HF_TOKEN }} ailurus1/text2image-bot:latest