name: Deploy with changes

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        uses: ./.github/workflows/lint.yaml
      - name: Build and Push
        uses: ./.github/workflows/build_push_docker_image.yaml
        secrets: 
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: deploy
        run: |
          docker run --env TG_TOKEN=${{ secrets.TG_TOKEN }} --env HF_TOKEN=${{ secrets.HF_TOKEN }} -it text2image-bot:latest