ame: Run linter for Python 3

on:
  push:
    branches: [ "master" ]
  pull_requiest:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        uses: sunnysid3up/python-linter@master
        with:
          source: app
          pylint-options: "--rcfile=setup.cfg"
